<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Platypus</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body
        {
            margin:              50px 0 0 0;
            padding:             0;
            width:               100%;
            font-family:         "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align:          center;
            color:               #aaa;
            font-size:           18px;
            background-image:    url("/images/Perry_the_platypus.png");
            background-repeat:   no-repeat;
            background-size:     250px auto;
            background-position: 13% 130px;
        }

        h1
        {
            color:          #719e40;
            letter-spacing: -3px;
            font-family:    'Lato', sans-serif;
            font-size:      120px;
            font-weight:    200;
            margin-bottom:  0;
            display: inline-block;
            padding:30px;
        }

        .rainbow
        {
            -webkit-box-sizing: content-box;
            -moz-box-sizing:    content-box;
            box-sizing:         content-box;
            cursor:             pointer;
            border:             none;
            font:               normal normal bold 100px/normal "Bad Script", Helvetica, sans-serif;
            color:              rgba(0, 0, 0, 0);
            text-align:         center;
            -o-text-overflow:   clip;
            text-overflow:      clip;
            text-shadow:        3px 0 0 rgb(217, 31, 38), 6px 0 0 rgb(226, 91, 14), 9px 0 0 rgb(245, 221, 8), 12px 0 0 rgb(5, 148, 68), 15px 0 0 rgb(2, 135, 206), 18px 0 0 rgb(4, 77, 145), 21px 0 0 rgb(42, 21, 113);
            -webkit-transition: all 600ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            -moz-transition:    all 600ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            -o-transition:      all 600ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            transition:         all 600ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

        .rainbow:hover
        {
            text-shadow:        -3px 0 0 rgb(217, 31, 38), -6px 0 0 rgb(226, 91, 14), -9px 0 0 rgb(245, 221, 8), -12px 0 0 rgb(5, 148, 68), -15px 0 0 rgb(2, 135, 206), -18px 0 0 rgb(4, 77, 145), -21px 0 0 rgb(42, 21, 113);
            -webkit-transition: all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            -moz-transition:    all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            -o-transition:      all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
            transition:         all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }
    </style>
</head>
    <body>
    <br><br>
    <h1 class="rainbow">Platypus</h1>
    <br><br><br>
    <div>a fancy hashtag based feedback tool for universities inspired by jodel and twitter</div>
    </body>
</html>
